---
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Project
metadata:
  annotations:
    cnrm.cloud.google.com/auto-create-network: "true"
  name: pii-poc-tg0518
spec:
  billingAccountRef:
    external: 011182-601A30-7C163B
  folderRef:
    external: "764417221947"
  name: pii-poc-tg0518
  resourceID: pii-poc-tg0518
