# Use an official Node.js runtime as a parent image
FROM node:16

# Copy all files to the container
COPY index.js .
COPY package.json .

# Install app dependencies
RUN npm install

# Set the command to run the app
CMD ["node", "index.js"]
