---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.pii_svc }}-ksa"
  namespace: terraform-managed-namespace
  annotations:
    iam.gke.io/gcp-service-account: "{{ .Values.pii_svc }}-gsa@{{ .Values.project }}.iam.gserviceaccount.com"
---
# https://github.com/GoogleCloudPlatform/k8s-config-connector/tree/master/samples/tutorials/workload-identity
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: "{{ .Values.pii_svc }}-gsa"
spec:
  displayName: "Created with CC for {{ .Values.pii_svc }}"
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: "{{ .Values.pii_svc }}-iam-policy-member-wi"
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: "{{ .Values.pii_svc }}-gsa"
  role: roles/iam.workloadIdentityUser
  member: "serviceAccount:{{.Values.project}}.svc.id.goog[terraform-managed-namespace/{{ .Values.pii_svc }}-ksa]"
---
# Give the gsa roles/storage.admin
# https://cloud.google.com/config-connector/docs/concepts/namespaces-and-projects
# can't get this to work because the project was created before the cnrm was enabled
# so the project doesn't exist in cnrm, so I can't reference it
# https://cloud.google.com/config-connector/docs/how-to/import-export/overview
# https://cloud.google.com/config-connector/docs/how-to/import-export/export

# well that was a fuckin dooozey
# need to have org to do this

apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: "{{ .Values.pii_svc }}-iam-policy-storage-admin"
spec:
  resourceRef:
    kind: Project
    name: "{{ .Values.project }}"
  member: "serviceAccount:{{ .Values.pii_svc }}-gsa@{{ .Values.project }}.iam.gserviceaccount.com"
  role: roles/storage.admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: "{{ .Values.pii_svc }}-deploy"
  name: "{{ .Values.pii_svc }}-deploy"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.pii_svc }}-deploy"
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: "{{ .Values.pii_svc }}-deploy"
    spec:
      containers:
        - image: google/cloud-sdk
          name: "{{ .Values.pii_svc }}-container"
          resources: {}
          command: ["/bin/bash", "-c", "--"]
          args: ["while true; do sleep 30; done;"]
      serviceAccountName: "{{ .Values.pii_svc }}-ksa"
