---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.pii_svc }}-ksa"
  namespace: terraform-managed-namespace
  annotations:
    iam.gke.io/gcp-service-account: "{{ .Values.pii_svc }}-gsa@{{ .Values.project }}.iam.gserviceaccount.com"
---
# https://github.com/GoogleCloudPlatform/k8s-config-connector/tree/master/samples/tutorials/workload-identity
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: "{{ .Values.pii_svc }}-gsa"
spec:
  displayName: "Created with CC for {{ .Values.pii_svc }}"
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: "{{ .Values.pii_svc }}-iam-policy"
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: "{{ .Values.pii_svc }}-gsa"
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - "serviceAccount:{{.Values.project}}.svc.id.goog[terraform-managed-namespace/{{ .Values.pii_svc }}-ksa]"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: "{{ .Values.pii_svc }}-deploy"
  name: "{{ .Values.pii_svc }}-deploy"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.pii_svc }}-deploy"
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: "{{ .Values.pii_svc }}-deploy"
    spec:
      containers:
        - image: google/cloud-sdk
          name: "{{ .Values.pii_svc }}-container"
          resources: {}
          command: ["/bin/bash", "-c", "--"]
          args: ["while true; do sleep 30; done;"]
      serviceAccountName: "{{ .Values.pii_svc }}-ksa"
